# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1822e2ef1879bd9ea7aa2e7717ce236a1b665eba809a327ce5135e4296dde91547ad37bb326422c23e68a8ba86ff3e6bf459abec1196c92815bb2bd572ad9b8

test:
  secret_key_base: cf352d677ee472028cf7d0166dd825e5404f1cf7937a87d12129ed69539775d33c43166fbe1c79f724cf6ca4d71cb46c313866c279c62974d32657ede6594b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
