#:schema node_modules/wrangler/config-schema.json
name = "menon-api"
compatibility_date = "2024-04-29"
compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DATABASE"
database_name = "menon"
database_id = "24f68fb1-b0d3-412c-beb2-42abf254568b"
